version: '3.8'

services:
  viz-chart-mcp-sse:
    image: ghcr.io/9999-12-31/plugin-viz-chart/viz-chart-mcp-sse:0.0.1
    container_name: viz-chart-mcp-sse
    restart: unless-stopped
    build:
      context: ./sse
      dockerfile: Dockerfile
    ports:
      - "1123:1123"

  viz-chart-mcp-streamable:
    image: ghcr.io/9999-12-31/plugin-viz-chart/viz-chart-mcp-streamable:0.0.1
    container_name: viz-chart-mcp-streamable
    restart: unless-stopped
    build:
      context: ./streamable
      dockerfile: Dockerfile
    ports:
      - "1122:1122"
