version: '3.8'

services:
  viz-chart-mcp-sse:
    image: ${REGISTRY:-ghcr.io/9999-12-31}/plugin-viz-chart/mcp-sse:latest
    container_name: viz-chart-mcp-sse
    restart: unless-stopped
    build:
      context: ./sse
      dockerfile: Dockerfile
    ports:
      - "1123:1123"

  viz-chart-mcp-streamable:
    image: ${REGISTRY:-ghcr.io/9999-12-31}/plugin-viz-chart/mcp-streamable:latest
    container_name: viz-chart-mcp-streamable
    restart: unless-stopped
    build:
      context: ./streamable
      dockerfile: Dockerfile
    ports:
      - "1122:1122"
